version: '3'

services:
  mysql:
    container_name: database
    hostname: ${DB_HOST}
    image: mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_INITDB_CHARSET: utf8mb4
    restart: always
    command: ["--log_bin_trust_function_creators=1"]
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
    healthcheck:
      test: mysql ${DB_NAME} --user=${DB_USER} --password='${DB_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5